// カタログが持つ意味付きアイコン名を、実際に描画する図形へ結び付ける表です。
// 型を網羅 Record にしているので、カタログへ名前を足すとここで型エラーになります。
import {
  ArchiveIcon,
  AvatarIcon,
  BackpackIcon,
  BadgeIcon,
  BarChartIcon,
  BellIcon,
  BookmarkIcon,
  CalendarIcon,
  ChatBubbleIcon,
  CodeIcon,
  ColorWheelIcon,
  CookieIcon,
  CubeIcon,
  DashboardIcon,
  EnvelopeClosedIcon,
  ExclamationTriangleIcon,
  FileTextIcon,
  GearIcon,
  GitHubLogoIcon,
  GlobeIcon,
  HeartIcon,
  IdCardIcon,
  LayersIcon,
  LightningBoltIcon,
  LockClosedIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MixerHorizontalIcon,
  Pencil1Icon,
  Pencil2Icon,
  PersonIcon,
  PlayIcon,
  QuoteIcon,
  ReaderIcon,
  RocketIcon,
  RulerSquareIcon,
  SpeakerLoudIcon,
  StarIcon,
  VideoIcon
} from "@radix-ui/react-icons"

import type { CategoryPresetIcon } from "~/catalogs/onboarding-category-presets"

type IconComponent = typeof ArchiveIcon

export const CATEGORY_PRESET_ICONS: Record<CategoryPresetIcon, IconComponent> = {
  archive: ArchiveIcon,
  avatar: AvatarIcon,
  backpack: BackpackIcon,
  badge: BadgeIcon,
  bell: BellIcon,
  bolt: LightningBoltIcon,
  bookmark: BookmarkIcon,
  calendar: CalendarIcon,
  card: IdCardIcon,
  chart: BarChartIcon,
  chat: ChatBubbleIcon,
  code: CodeIcon,
  container: CubeIcon,
  dashboard: DashboardIcon,
  document: FileTextIcon,
  envelope: EnvelopeClosedIcon,
  food: CookieIcon,
  gear: GearIcon,
  globe: GlobeIcon,
  heart: HeartIcon,
  layers: LayersIcon,
  lock: LockClosedIcon,
  magic: MagicWandIcon,
  mixer: MixerHorizontalIcon,
  music: SpeakerLoudIcon,
  note: Pencil1Icon,
  palette: ColorWheelIcon,
  pencil: Pencil2Icon,
  person: PersonIcon,
  play: PlayIcon,
  quote: QuoteIcon,
  reader: ReaderIcon,
  repository: GitHubLogoIcon,
  rocket: RocketIcon,
  ruler: RulerSquareIcon,
  search: MagnifyingGlassIcon,
  star: StarIcon,
  video: VideoIcon,
  warning: ExclamationTriangleIcon
}
